spring.application.name=LoggingApplication1

## Set logging level for your specific package
#logging.level.com.example.demo=DEBUG
#
## Optional: Format logs to show Date, Level, Thread, Class, and Message
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n