spring.application.name=kafka-producer-service
server.port=8080

#kafka bootstrap server
spring.kafka.producer.bootstrap-servers=localhost:9092

#serializers for key and value
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer